import { NextRequest, NextResponse } from "next/server";
import { GoogleGenerativeAI } from "@google/generative-ai";

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY || "");

export async function POST(req: NextRequest) {
  try {
    if (!process.env.GEMINI_API_KEY) {
      return NextResponse.json({ error: "Gemini API key not configured" }, { status: 500 });
    }

    const body = await req.json();
    const { transcription } = body;

    const model = genAI.getGenerativeModel({ model: "gemini-2.5-flash" });

    const prompt = `
You are an expert audio transcription editor. I will give you a raw transcription generated by an STT engine.
Your task is to:
1. Fix any obvious hallucinated words or wrongly recognized homonyms based on context.
2. Add proper punctuation, casing, and paragraph breaks.
3. If it seems like a conversation, attempt to add speaker labels (Speaker A, Speaker B) if the flow suggests a back-and-forth.
4. Below the corrected text, add a short section titled "--- Summary & Keywords ---" and provide a 1-sentence summary and 3-5 keywords.

Raw Transcription:
"${transcription}"

Please provide only the corrected text and the summary section.
    `;

    const result = await model.generateContent(prompt);
    const response = await result.response;
    const text = response.text();

    return NextResponse.json({ insight: text });
  } catch (error: any) {
    console.error("AI Insight error:", error);
    return NextResponse.json(
      { error: error.message || "Failed to generate AI insight" },
      { status: 500 }
    );
  }
}
